### ISSUE TITLE
Recommended displays?

### ISSUE THREAD

**Issue by znmeb** [pimoroni/picovision#81]
The only HDMI display I have is a 10.1 inch 1920X1200 touchscreen. Will that work with the much smaller modes supported by the PicoVision? If not, what display would you recommend?

**Comment by MichaelBell** [comment]
Generally most displays will support at least 640x480, maybe you can try connecting something else using that resolution to confirm?

**Comment by znmeb** [comment]
I have the Python examples sort of working with my 10.1 inch display. The menu comes up, and I can get "scrollgroups" and "sneks_and_ladders" to display, but the others seem to be overwhelming the "GPU" - the display reports "No Signal".

I took a look at the source and it appears that the two that work seem to be explicitly setting the display width and height to 320x240 and the others aren't doing that. So I'm not sure exactly what's going on - I'm not a Python programmer.

**Comment by znmeb** [comment]
OK - I just edited some of the broken ones and changed the settings and they work now. Were these examples tested on some other kind of hardware with more power than a PicoVision?

**Comment by Gadgetoid** [comment]
> seem to be overwhelming the "GPU" - the display reports "No Signal".

That could just mean the display, for whatever reason, is unhappy with the output signal. An unfortunate consequence of us producing weird HDMI modes with a microcontroller.

We all have different displays with different tolerances for weirdness. It might be worth running "screenmodes.py" to see if there are particular modes your display (or board) is unhappy with: https://github.com/pimoroni/picovision/blob/main/examples/screenmodes.py

While I don't expect anyone to rush out and buy a new display, for full disclosure I've done most of my testing with: https://www.elecrow.com/crowview-ultimate-14-portable-ultralight-dual-monitor-support-multiple-system-and-13-16-5-laptops.html

>  Were these examples tested on some other kind of hardware with more power than a PicoVision?

In theory no, but in practice different PicoVision boards, and by extension their RP2040-based GPUs, have different tolerances for overclocking. We test all boards at high overclocks to make sure they handle all the modes we support but it could be a case of a less-than-perfect board slipping through.

**Comment by MichaelBell** [comment]
If the blue LED is still fading on and off, the "GPU" is still running normally.  If the "GPU" crashes you normally get a red screen, and if it is overloaded you can get horizontal red lines on the screen.  No signal is more likely to be that your display doesn't like the HDMI signal from the PicoVision (e.g. because it doesn't support the display resolution).

Are examples that run at 640x480 working for you?  PicoVision uses the same timing for the HDMI signal at 640x480 and 320x240, although the exact symbol encoding is different.

I think a number of examples use 720x480 - if 640x480 works and 720x480 does not then it is likely your display simply doesn't support 720x480.

**Comment by technolhodgy** [comment]
Before I did the python version of screenmodes.py I wrote it in C/C++
https://github.com/technolhodgy/picovision-demos/tree/main

Functionally it it almost the same, the python version I added a feature to detect if the widescreen micropython build was in use, and block non-widescreen modes if only using the normal build.

All modes should be accessible from the C++ or the widescreen build.

**Comment by znmeb** [comment]
Thanks!1 I have the display hooked up to a 64-bit PiOS system now and there are two modes I can use for the competition - 720x576 and 720x480. So once I understand the Python and C++ APIs I can proceed.
